### ISSUE TITLE
Home page with Navbar

### ISSUE THREAD

**Issue by gopivaibhav** [gopivaibhav/SPARK-website#1]
https://in.pinterest.com/pin/325103666862320075/feedback/?invite_code=59effa33aef441c7a8b8e8a3c6034057&sender_id=609604636969803998

Replicate this in the index.html which is already present in the repository
U can use temporary images and texts for now and send a PR to main branch from the branch, which you created in your repo

**Comment by dilippatnana** [comment]
I'd like to get assigned to this

**Comment by gopivaibhav** [comment]
Ok. Also this issue seems to be very easy and so small. So. I will be sending you a navbar source code too and you have to work on this as well.

**Comment by dilippatnana** [comment]
Should I make the only magazine or the whole jpg?

**Comment by gopivaibhav** [comment]
> Should I make the only magazine or the whole jpg?

No, only cover page should be made which is our home page

**Comment by gopivaibhav** [comment]
Navbar can be made using this [source code](https://www.youtube.com/watch?v=nMGVwP3ww2M)
