### ISSUE TITLE
Articles Page

### ISSUE THREAD

**Issue by gopivaibhav** [gopivaibhav/SPARK-website#2]
https://codepen.io/Booligoosh/pen/mKPpQp

Use this to make an articles page in articles.html file (Create one) and send the PR to main branch of this repo from the branch which you created in your repo

**Comment by sakshi2407** [comment]
Please assign this issue to me

**Comment by gopivaibhav** [comment]
Done

**Comment by gopivaibhav** [comment]
Also, this issue seems too basic for me. So. I will be adding another task to it. Till then you can send a PR by completing the given task
