### ISSUE TITLE
News section

### ISSUE THREAD

**Issue by gopivaibhav** [gopivaibhav/SPARK-website#3]
https://codepen.io/oliviale/pen/BaoXOOP 

Use this to make a news page in news.html file (Create one) and send the PR to main branch of this repo from the branch which you created in your repo

**Comment by sakshi2407** [comment]
Pls assign me this issue.

**Comment by pranjalad12** [comment]
@gopivaibhav sir, Please assign this Issue to me, Thanks.

**Comment by gopivaibhav** [comment]
> @gopivaibhav sir, Please assign this Issue to me, Thanks.

Okk, sure!!
