### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by gopivaibhav** [gopivaibhav/SPARK-website#4]
https://codepen.io/LIMESTA/pen/KKPbvpL

Use this to make a team page in team.html file (Create one) and send the PR to main branch of this repo from the branch which you created in your repo.

The Team cards are not at all good but we dont wanna waste the time. So, we are continuing with these cards and if you guys find some good layouts for team cards, feel free to put them in whatsapp group

**Comment by gopivaibhav** [comment]
Add 4 cards using https://www.youtube.com/watch?v=aTK3vCzjzCo in a same row. Also, Make these cards responsive

**Comment by gopivaibhav** [comment]
Also, add the Same effect for all the social media links in every card
Which should be this effect https://www.youtube.com/watch?v=Vm_te-D25D4&t=0s

**Comment by THE-AryanKumar** [comment]
Can you pls /assign this issue to me. @gopivaibhav

**Comment by gopivaibhav** [comment]
Assigned you @THE-AryanKumar

**Comment by gopivaibhav** [comment]
Add 10 - 12 cards using this [code](https://codepen.io/petebot/pen/bGgbPq?editors=1000)

**Comment by gopivaibhav** [comment]
@THE-AryanKumar Search for some team cards

**Comment by THE-AryanKumar** [comment]
@gopivaibhav sir I'm still working on social media effects and more. ill update it soon

**Comment by gopivaibhav** [comment]
Prioritise your work 
Implementing new Team cards >> Adding extra effects over social media icons @THE-AryanKumar

**Comment by THE-AryanKumar** [comment]
sir I have pushed the team cards, let me know if you want to change
