### ISSUE TITLE
New articles page

### ISSUE THREAD

**Issue by gopivaibhav** [gopivaibhav/SPARK-website#5]
https://www.youtube.com/watch?v=nM-30MdKNc4

Use this tutorial and make a new file named new-articles.html and add stylesheets with the name new-articles.css

**Comment by gopivaibhav** [comment]
Also make 3 dummy articles using this code https://codepen.io/JavaScriptJunkie/pen/WgRBxw

**Comment by THE-AryanKumar** [comment]
Sir pls /assign this issues to me @gopivaibhav

**Comment by gopivaibhav** [comment]
> Sir pls /assign this issues to me @gopivaibhav 

Done
